language: python

python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

# flake8 is a linting tool
script:
  - docker-compose run app sh -c "django-admin.py test && flake8"